include("Tulip.jl")
include("./IPM/QNC/load_problems.jl")
include("./exemplos/criar_modelo.jl")
println("Execute o comando testar(nome_ou_numero) para testar um problema.")
println("Use testar(nome_ou_numero, 1) para habilitar os prints.")
